default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: felipe
  password: "123456"
  host: localhost

development:
  <<: *default
  database: nf_emitter_development

test:
  <<: *default
  database: nf_emitter_test

production:
  <<: *default
  database: nf_emitter_production
  username: felipe
  password: "123456"
  host: localhost
